name: Apikey properties
description: Get apikey properties from secret on github
runs:
  using: "composite"
  steps:
    - run: |
        APIKEY_PROPERTIES_ASC_FILE="apikey_properties.asc"
        echo "${{ secrets.APIKEY_PROPERTIES}}">>"${APIKEY_PROPERTIES_ASC_FILE}"
        gpg -d --batch --passphrase "$(echo "${{ secrets.PASSWORD }}" | base64 --decode)" "${APIKEY_PROPERTIES_ASC_FILE}"> "apikey.properties"
      shell: bash