name: Workflow - Develop
on:
  push:
    branches:
      - 'develop'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x gradlew
      - uses: ./.github/actions/keystore_p12
      - uses: ./.github/actions/keystore_properties
      - uses: ./.github/actions/apikey_properties
      - uses: ./.github/actions/run_tests
      - uses: ./.github/actions/build_apk
      - uses: actions/upload-artifact@v3
        with:
          name: development-release-apk
          path: app/build/outputs/apk/development/release/app-development-release.apk