name: Workflow - Feature
on:
  push:
    branches:
      - 'feature/*'
jobs:
  build_apk:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x gradlew
      - uses: ./.github/actions/keystore_p12
      - uses: ./.github/actions/keystore_properties
      - uses: ./.github/actions/apikey_properties
      - uses: ./.github/actions/run_tests