name: Workflow - Feature
on:
  push:
    branches:
      - 'feature/*'
jobs:
  build_apk:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x gradlew
      - uses: ./.github/actions/get_secrets
        with:
          password: ${{ secrets.PASSWORD }}
          keystore_p12: ${{ secrets.KEYSTORE_P12 }}
          keystore_properties: ${{ secrets.KEYSTORE_PROPERTIES }}
          apikey_properties: ${{ secrets.APIKEY_PROPERTIES }}
      - uses: ./.github/actions/run_tests